version: "3.8"
services:
  chrome-standalone:
    image: selenium/standalone-chrome:4.13.0
    hostname: chrome
    container_name: chrome-standalone
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_MAX_SESSIONS=5

  backend:
    build:
      context: .
      target: production # replace with development to use debug better
    container_name: backend
    ports:
      - "8000:8080"
    env_file:
      - .env
    volumes:
      - .:/app

  redis:
    image: redis:7.2
    hostname: redis_hostname
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:13
    hostname: postgres_hostname
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=stockly
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"

volumes:
  redis_data:
  postgres_data: