version: "3"
services:
  firefox-standalone:
    image: selenium/standalone-firefox:4.13.0
    hostname: firefox
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_MAX_SESSIONS=5