version: "3.8"
services:
  firefox-standalone:
    image: selenium/standalone-firefox:4.13.0
    hostname: firefox
    container_name: firefox-standalone
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_MAX_SESSIONS=5

  backend:
    build:
      context: .
      target: production # replace with development to use debug better
    container_name: backend
    ports:
      - "8000:8080"
    env_file:
      - .env
    volumes:
      - .:/app

  redis:
    image: redis:7.2
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

volumes:
  redis_data: