"""
Django settings for stockly project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path


def get_env(env_key: str, default=None) -> any:
    try:
        return os.environ[env_key]
    except KeyError as ex:
        if default:
            return default
        raise ValueError(f"No {env_key} found. Please set the {env_key} environment variable in the .env file.")


BASE_DIR = Path(__file__).resolve().parent.parent

# environment variables
SECRET_KEY = get_env('DJANGO_SECRET_KEY')
REDIS_CACHE_HOST = get_env('REDIS_HOST', 'redis_hostname')
REDIS_CACHE_PORT = get_env('REDIS_CACHE_PORT', '6379')

POSTGRES_HOST = get_env('POSTGRES_HOST', 'postgres_hostname')
POSTGRES_PORT = get_env('POSTGRES_PORT', '5432')
POSTGRES_USER = get_env('POSTGRES_USER', 'postgres')
POSTGRES_PASSWORD = get_env('POSTGRES_PASSWORD', 'secret')
POSTGRES_DATABASE = get_env('POSTGRES_DATABASE', 'stockly')

POLYGON_API_KEY = get_env('POLYGON_API_KEY')
SCRAPYD_ENDPOINT = get_env('SCRAPYD_ENDPOINT')

SELENIUM_COOKIES_FILE_JSON = BASE_DIR / 'cookies.json'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(get_env('DJANGO_DEBUG', 0))

ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # external
    'django_guid',
    # internals
    'stockly.stocks'
]

MIDDLEWARE = [
    'django_guid.middleware.guid_middleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stockly.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stockly.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': POSTGRES_HOST,
        'PORT': POSTGRES_PORT,
        'USER': POSTGRES_USER,
        'PASSWORD': POSTGRES_PASSWORD,
        'NAME': POSTGRES_DATABASE,
    }
}

# Cache Redis
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_CACHE_HOST}:{REDIS_CACHE_PORT}/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'correlation_id': {'()': 'django_guid.log_filters.CorrelationId'},
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} [{correlation_id}] {message}',
            'style': '{',
        },
        'with_extra': {
            '()': 'stockly.extra_logging.ExtraFormatter',
            'format': '{levelname} [{asctime}] {name}.{funcName} [{correlation_id}] - {message}',
            'style': '{',
        },
    },
    'handlers': {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            'filters': ['correlation_id']
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'django.log',
            'formatter': 'with_extra',
            'filters': ['correlation_id']
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'stockly': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        }
    },
}
