name: Build Docker Images of Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List directory contents (for debugging)
        run: ls -la

      - name: Copy example .env to .env
        run: cp .env.example .env

      - name: Build
        run: docker-compose build